### ISSUE TITLE
tslib missing from dependencies

### ISSUE THREAD

**Issue by MCTaylor17** [GDGToulouse/devfest-theme-hugo#10]
`npm run build` does not work without first installing `tslib`.

**Comment by ilaborie** [comment]
I cannot reproduce the issue: I've try to drop my `node_module` and check after a fresh install of npm packages, and my `npm run build` works.
Maybe it's the issue depends on the OS, or the node/npm version ?
(I'm on OSX 10.15, node 13.9, npm 6.14)

Note: I also have bumped dependencies, maybe it could improve the situation

**Comment by MCTaylor17** [comment]
I haven't heard of TS packages installed in directly in Node or operating systems. The package may be installed globally on your machine.  Try running `npm uninstall -g tslib`.

We decided to go in a different direction so feel free to close the issue if you believe it's an environment problem.

**Comment by ilaborie** [comment]
OK, thanks for your feedback.
