### ISSUE TITLE
Bug: `google_news.html` template is removed from upstream GoHugoio repo.

### ISSUE THREAD

**Issue by DhairyaMajmudar** [GDGToulouse/devfest-theme-hugo#32]
`google_news.html` template is now removed from the upstream [gohugoio repo](https://github.com/gohugoio/hugo/)

https://github.com/gohugoio/hugo/commit/66f94b4945e804f10be0a04d1365bb3c6e1a4c05

And this template is being used in the template as of which we are facing errors while running the command `hugo server`

![image](https://github.com/GDGToulouse/devfest-theme-hugo/assets/124715224/35627d9b-0f59-4157-882a-30ce17e18e54)

**Comment by DhairyaMajmudar** [comment]
Hello, @ilaborie we at [JSON Schema org.](https://github.com/json-schema-org/) are creating a website for the upcoming conf. 
as of which template is used but while creating the website my builds are failing due this issue can you pls. kindly resolve this.

Thank you

cc : @benjagm @matrixise @cschaffner

**Comment by ilaborie** [comment]
> Hello, @ilaborie we at [JSON Schema org.](https://github.com/json-schema-org/) are creating a website for the upcoming conf. as of which template is used but while creating the website my builds are failing due this issue can you pls. kindly resolve this.
> 
> Thank you
> 
> cc : @benjagm @matrixise @cschaffner

Sorry but I'm not maintaining this project anymore.
You can still fork it and fix the issue.

**Comment by DhairyaMajmudar** [comment]
Thanks a lot for your quick reply. I have been trying to fix it.
