### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by MCTaylor17** [GDGToulouse/devfest-theme-hugo#9]
I found this listed on the [JAMstack Themes page](https://jamstackthemes.dev/theme/devfest-toulouse-theme/) and thought it looks pretty great!

I see it's under active development which is a definite plus, but seeing WIP commits on master makes me a little unsure whether it's safe to fork.

Is master more or less in a ready state?

**Comment by ilaborie** [comment]
Let's say that as long as we organize the Devfest Toulouse, this template is bound to change.
On the other hand, it is quite usable as such.

So I think you can use it, and adapt it to your needs if you take the time to see how [Hugo](https://gohugo.io/) works.

(Sorry for the messy history, we haven't been very rigorous on this point.)
